### ISSUE TITLE
compounds vs spectraData?

### ISSUE THREAD

**Issue by meowcat** [michaelwitting/MsBackendMassbank#23]
Hi,

I was wondering why in MsBackendMassbankSql, the metadata output is separated into the regular `spectraData` and the proprietary `compounds`. Or rather, I understand why, but I wonder if it is good / necessary / there is an alternative. In practice, this means that for using multiple backends as sources for MS2 matching, I do:

```
spectra_data <- spectraData(ms2_candidates)

if(existsMethod(compounds, class(ms2_candidates@backend))) {
  cpds_data <- compounds(ms2_candidates)
  cpds_data$compound_id <- NULL
  joined_data <- cbind(spectra_data, cpds_data)
}
else
  joined_data <- spectra_data
}
```

It doesn't seem like I should have to do this. Opinions?

**Comment by jorainer** [comment]
Hm, I see your point. As an alternative we could always load/add the compound annotations into the `spectraData`. Problem is that this will most likeky slow down everything, because it involves several SQL joins on the database side. That was also the main reason I did not want to do that in first place.

Do you have a different suggestion/solution?

Note that there is also the backend for `CompoundDb` databases that works in the same way.

**Comment by jorainer** [comment]
Actually, I will test the performance with and without including the additional compound annotations. I see that it makes more sense to also report them in the `spectraData` - if it does not have a tremendous impact on performance.

**Comment by jorainer** [comment]
@meowcat , PR #24 contains the fixes that should solve your issue: `spectraData` contains then also the compound annotation. I checked the performance and that is comparable. Things like `compareSpectra` are not at all affected because these only work on the peak matrices.

Note that if you want to use this package version you will also need to fix your MassBank MySQL database. Specifically, you should rename the `compound` view into `ms_compound` (see PR #22 for more info). You could do that with the SQL commands below:

```sql
drop view compound;

create view ms_compound as select
       COMPOUND.ID as compound_id,
       COMPOUND.CH_FORMULA as formula,
       COMPOUND.CH_EXACT_MASS as exactmass,
       COMPOUND.CH_SMILES as smiles,
       COMPOUND.CH_IUPAC as inchi,
       (select DATABASE_ID from CH_LINK where CH_LINK.COMPOUND = COMPOUND.ID
       and CH_LINK.DATABASE_NAME = 'INCHIKEY') as inchikey,
       (select DATABASE_ID from CH_LINK where CH_LINK.COMPOUND = COMPOUND.ID
       and CH_LINK.DATABASE_NAME = 'CAS') as cas,
       (select DATABASE_ID from CH_LINK where CH_LINK.COMPOUND = COMPOUND.ID
       and CH_LINK.DATABASE_NAME = 'PUBCHEM') as pubchem
from COMPOUND;
```

**Comment by meowcat** [comment]
Awesome! Thanks a ton.

**Comment by jorainer** [comment]
It's now merged into the master branch; but as detailed above you need to rename the view in the MassBank database.

**Comment by jorainer** [comment]
Note: MassBank provides now also an updated MySQL dump with the renamed *compound* table. So, you can now directly use the *official* MySQL database dump with this version of `MsBackendMassbank`.

I'm closing the issue now, feel free to reopen if needed @meowcat

**Comment by meowcat** [comment]
I can confirm that everything works as desired. Thanks!
